### ISSUE TITLE
Several questions about switch-hawaii.

### ISSUE THREAD

**Issue by KevinXo** [switch-hawaii/main#1]
Dear sir,
       after I run "switch solve --solver gurobi".I don't know which inputs folder corresponds to the outputs folder.And how can I change the inputs folder to get different outputs?WHats more,only through the inputs and outputs folder,I cant understand the scenario totally，do you have more  detailed instructions about them?
      Anthor one is could SWITCH solve energy storages siting and sizing problems？
      Thank you a lot ,sir.

**Comment by mfripp** [comment]
You can change the inputs directory by setting the `--inputs-dir` flag in options.txt, scenarios.txt or on the command line, as mentioned at https://github.com/switch-hawaii/main/blob/master/readme.txt . 

You can change the outputs directory by setting `--outputs-dir` in the same places. 

You can get descriptions of all available flags like this by running `switch solve --help`. 

You can also see examples of useful combinations of flags by looking in scenarios.txt. Each line in there includes settings to run the model for one distinct scenario. You can solve all of them by running `switch solve-scenarios` or solve one of them by running `switch solve-scenarios --scenario <name>`, where `<name>` is one of the scenario names shown in scenarios.txt. You can also just run `switch solve` with the extra flags you find in scenarios.txt.

Looking in scenarios.txt may also be the link you need to see how the example outputs are created from the inputs. I'm not sure if that was your second question, or if you have more specific questions about what is included in the input and output directories. The parameters and sets defined in the input files are documented in the Supplementary Material at https://doi.org/10.1016/j.softx.2019.100251 . Let me know if you have more questions beyond that.

Switch is certainly well suited for a storage siting and sizing problem. You could look at the [reserves_study_2018 repository](https://github.com/switch-hawaii/reserve_study_2018) for an example. The key idea is to define generation projects for each type of storage at each location where you might put it, then let Switch choose the size for the power and energy components. You will need to use the `switch_model.generation.extensions.storage` module for this. It is documented in the [Supplementary Material](https://ars.els-cdn.com/content/image/1-s2.0-S2352711018301547-mmc1.pdf) referenced above, or you can read the source code (with extensive comments) directly at https://github.com/switch-model/switch/blob/master/switch_model/generators/extensions/storage.py .
